INSERT INTO projects (
    project_name,
    project_logo_1,
    project_logo_2,
    project_description,
    project_overview_description_part_01,
    project_overview_description_part_02,
    project_overview_technologies,
    project_overview_duration,
    project_timeline_event_01_title,
    project_timeline_event_01,
    project_timeline_event_02_title,
    project_timeline_event_02,
    project_timeline_event_03_title,
    project_timeline_event_03,
    project_timeline_event_04_title,
    project_timeline_event_04,
    project_timeline_event_05_title,
    project_timeline_event_05,
    project_final_results_description_part_01,
    project_final_results_description_part_02,
    project_final_results_stat_01_title,
    project_final_results_stat_01,
    project_final_results_stat_02_title,
    project_final_results_stat_02,
    project_final_results_stat_03_title,
    project_final_results_stat_03,
    project_external_url
) VALUES (
    'Portfolio Platform: Full‑Stack Showcase',
    NULL,
    NULL,
    'A modern portfolio platform demonstrating end‑to‑end full‑stack skills, from resilient backend APIs and database design to a performant React front‑end with thoughtful UX.',
    'This project consolidates lessons from prior client work into a cohesive app.',
    'A typed Node.js/Express API with PostgreSQL migrations and seeds, Dockerized environments, and a Vite + React client styled with Tailwind.',
    'TypeScript, Node.js, Express, PostgreSQL, Docker, React, Vite, Tailwind',
    'Ongoing',
    'Kickoff',
    'project structure, TypeScript setup, Docker Compose for dev/prod.',
    'Database',
    'schema design for projects, robust seeding and migrations.',
    'API',
    'Express controllers and routes for project data, with tests.',
    'Client',
    'feature modules for overview, timeline, and results sections.',
    'Launch',
    'production build pipeline and deployment verification.',
    'A single, cohesive portfolio increased delivery speed and consistency.',
    'Clear data modeling and content structure simplified adding new projects and improved maintainability across the stack.',
    'Iteration speed',
    'Faster iteration on content updates',
    'Design consistency',
    'Consistent UI/UX across features',
    'Developer experience',
    'Reduced setup friction for new features',
    'https://www.martinezdylan.dev'
);