-- Project 1: Belen Abdon: Building a Brand
INSERT INTO projects (
    project_id,
    project_name,
    project_logo_1,
    project_logo_2,
    project_description,
    project_overview_description_part_01,
    project_overview_description_part_02,
    project_overview_technologies,
    project_overview_duration,
    project_timeline_event_01_title,
    project_timeline_event_01,
    project_timeline_event_02_title,
    project_timeline_event_02,
    project_timeline_event_03_title,
    project_timeline_event_03,
    project_timeline_event_04_title,
    project_timeline_event_04,
    project_timeline_event_05_title,
    project_timeline_event_05,
    project_final_results_description_part_01,
    project_final_results_description_part_02,
    project_final_results_stat_01_title,
    project_final_results_stat_01,
    project_final_results_stat_02_title,
    project_final_results_stat_02,
    project_final_results_stat_03_title,
    project_final_results_stat_03,
    project_external_url
) VALUES (
    1,
    'Belen Abdon: Building a Brand',
    NULL,
    NULL,
    'Belen wanted a website that would highlight her professional experience as well as her values and her personal brand. The plan was to create a clear and easy to navigate site. The result is more than a personal brand website, it is a platform where she actively expresses herself, reaches new clients, grows her network, and reinforces credibility on the way, an all-in-one solution.',
    'This project was my first real-world experience, a foundational milestone in my career. Belen wanted a website that reflected both her professional expertise and core values—a digital manifesto of her way of working.',
    'The process became an intensive lesson in problem-solving, with challenges ranging from learning Elementor’s framework to building a responsive and accessible site for the first time. Over three months, I navigated each difficulty, focusing on usability and performance. The result was a clean, fast, and accessible site that presents Belen as a professional and efficient individual, while maintaining an approachable and authentic presence that helps her to serve clients effectively.',
    'JavaScript, PHP, MySQL, HTML, CSS',
    '3 months',
    'Start',
    'Initial layout in Elementor; built with docs and community help.',
    'Text and images',
    'Added copy and images; standardized on WebP for performance.',
    'Development',
    'Implemented animations and clear navigation focused on CTAs.',
    'Design eye',
    'Made site responsive and accessible for inclusive, device-wide UX.',
    'Results',
    'Monitored impact; supported bugs and edge cases post-launch.',
    'The successful launch of Belen''s website was a significant event. She was delighted with the final solution and continues to use it on a daily basis to connect with her clients and expand her professional network.',
    'Just a month later, she reported an increase of site total visits of 13% MoM, and an increase on the conversion rate of 2% YoY.',
    'Site total visits MoM',
    '+13% MoM site total visits',
    'Sales conversion rate YoY',
    '+2% YoY sales conversion rate',
    NULL,
    NULL,
    'https://belenabdon.com/'
);

-- Project 2: BV Architecture: Design in Motion
INSERT INTO projects (
    project_id,
    project_name,
    project_logo_1,
    project_logo_2,
    project_description,
    project_overview_description_part_01,
    project_overview_description_part_02,
    project_overview_technologies,
    project_overview_duration,
    project_timeline_event_01_title,
    project_timeline_event_01,
    project_timeline_event_02_title,
    project_timeline_event_02,
    project_timeline_event_03_title,
    project_timeline_event_03,
    project_timeline_event_04_title,
    project_timeline_event_04,
    project_timeline_event_05_title,
    project_timeline_event_05,
    project_final_results_description_part_01,
    project_final_results_description_part_02,
    project_final_results_stat_01_title,
    project_final_results_stat_01,
    project_final_results_stat_02_title,
    project_final_results_stat_02,
    project_final_results_stat_03_title,
    project_final_results_stat_03,
    project_external_url
) VALUES (
    2,
    'BV Architecture: Design in Motion',
    NULL,
    NULL,
    'Belen needed a portfolio site that trascended the expected, the ordinary. The goal was to create "a visual experience" that would not just display architectural projects, but also, reflect her innovative and unconventional approach to design. The result stood out: the site became a talking point among peers and was even featured on a leading architectural blog in Spain.',
    'This project was more than building a portfolio; it was about creating a digital reflection of Belen''s design philosophy. The challenge was to deliver a unique and interactive experience—something rare, beautiful, and technically solid.',
    'The first impression when visiting the site is the seamless flow of the gallery, where animations feel natural and carefully assembled. Achieving this required a toolkit centered on JavaScript to power the motion and interactivity, paired with Linux and additional technologies for a robust server configuration. Overcoming the technical difficulties was as important as preserving the elegance of the design. The finished product proves that a website can move beyond being a static showcase; it can become an immersive journey where users actively play and engage with the work instead of just looking.',
    'JavaScript, MariaDB, HTML, CSS',
    '2 months',
    'Start',
    'Initialized repo; provisioned DigitalOcean droplet.',
    'Text and images',
    'Curated content; adapted assets to the custom carousel.',
    'Server',
    'Hardened server; followed CIS benchmarks on Linux.',
    'Last touch',
    'Ensured complex layout works across sizes; aligned with WCAG.',
    'Launch & post-launch',
    'Tested in prod-like environments; provided extended support.',
    'The client''s enthusiastic response to the final website was really gratifying. Belen adopted the website as her primary portfolio.',
    'Within a month of its release, total visits rose up to 20% MoM and the website was featured in a prominent Spanish architectural blog for its outstanding design.',
    'Site total visits MoM',
    '+20% MoM site total visits',
    'Press feature',
    'Site featured on Dazeen',
    NULL,
    NULL,
    'https://bvarchitecture.es/'
);

-- Project 3: En Marte: From Another Planet
INSERT INTO projects (
    project_id,
    project_name,
    project_logo_1,
    project_logo_2,
    project_description,
    project_overview_description_part_01,
    project_overview_description_part_02,
    project_overview_technologies,
    project_overview_duration,
    project_timeline_event_01_title,
    project_timeline_event_01,
    project_timeline_event_02_title,
    project_timeline_event_02,
    project_timeline_event_03_title,
    project_timeline_event_03,
    project_timeline_event_04_title,
    project_timeline_event_04,
    project_timeline_event_05_title,
    project_timeline_event_05,
    project_final_results_description_part_01,
    project_final_results_description_part_02,
    project_final_results_stat_01_title,
    project_final_results_stat_01,
    project_final_results_stat_02_title,
    project_final_results_stat_02,
    project_final_results_stat_03_title,
    project_final_results_stat_03,
    project_external_url
) VALUES (
    3,
    'En Marte: From Another Planet',
    NULL,
    NULL,
    'The vision for EN MARTE was to create more than an online store; it was about crafting a seamless shopping experience that preserved its laid-back aesthetic while ensuring an intuitive UX to drive sales. The result not only met but surpassed expectations, achieving a 17.4% YoY sales increase and a 4% MoM boost in conversion.',
    'The EN MARTE project transported me back to my earlier experience as a CX director, where the focus was always on crafting memorable journeys. This time, the challenge was to design an online store for Camila’s users that balanced her brand’s laid-back aesthetic with a clear and effective path to purchase. Navigation and ease of use became top priorities, ensuring products were not only displayed beautifully but also encouraged sales.',
    'A further challenge was working within Shopify’s Liquid framework, which required adapting both design and logic to fit the platform’s constraints. Ultimately, the result was deeply rewarding: Camila quickly adopted the site as her main sales channel, and her business saw measurable success, with a 17.4% increase in sales year-over-year and a 4% month-over-month boost in conversion.',
    'Liquid, JavaScript, MySQL, HTML, CSS',
    '3 months',
    'Site config',
    'Implemented Shopify setup, payments, and Liquid best practices.',
    'Database seeding',
    'Created products and categories; structured collections.',
    'Fine-tuning',
    'Refined layouts, navigation, and header logic to boost conversion.',
    'Feedback loop',
    'Applied client feedback; shifted aesthetics to a laid-back style.',
    'Results',
    'Evaluated impact; supported issues and edge cases post-launch.',
    'The culmination of this project is an online store that not only empowers Camila to sell across Europe but also delivers measurable growth.',
    'Just months after launch, sales increased 17.4% year-over-year, with a 4% month-over-month boost in conversion. These results validate the design decisions, proving that a well designed and easy to use UX directly translates into business results.',
    'Total sales YoY',
    '+17.4% YoY total sales increase',
    'Sales conversion rate MoM',
    '+4% MoM sales conversion rate',
    'Sales channels expansion',
    'Instagram-only to multi-sales-channel',
    'https://enmarte.shop/'
);

-- Project 4: ISSAS: Alla Italiana
INSERT INTO projects (
    project_id,
    project_name,
    project_logo_1,
    project_logo_2,
    project_description,
    project_overview_description_part_01,
    project_overview_description_part_02,
    project_overview_technologies,
    project_overview_duration,
    project_timeline_event_01_title,
    project_timeline_event_01,
    project_timeline_event_02_title,
    project_timeline_event_02,
    project_timeline_event_03_title,
    project_timeline_event_03,
    project_timeline_event_04_title,
    project_timeline_event_04,
    project_timeline_event_05_title,
    project_timeline_event_05,
    project_final_results_description_part_01,
    project_final_results_description_part_02,
    project_final_results_stat_01_title,
    project_final_results_stat_01,
    project_final_results_stat_02_title,
    project_final_results_stat_02,
    project_final_results_stat_03_title,
    project_final_results_stat_03,
    project_external_url
) VALUES (
    4,
    'ISSAS: Alla Italiana',
    NULL,
    NULL,
    'Developed a modern e-commerce solution for ISSAS, a luxury jewelry brand in Copenhagen. The aim was to translate Monica’s taste in jewelry and fashion into a captivating digital experience that could support international expansion. The site delivered results quickly: a 10% MoM sales increase and first-ever cross-border orders from Sweden, Germany, and the Netherlands.',
    'The ISSAS project was a journey in translating a personal style into a compelling online presence, a brand.',
    'The minimalistic design aesthetic, inspired by Italian fashion, and a tight feedback loop led to a solution that reflected Monica''s identity, increased sales 10% MoM, and enabled the desired international expansion.',
    'Liquid, JavaScript, MySQL, HTML, CSS',
    '2 months',
    'Platform''s config',
    'Granted dev access; set up domain DNS.',
    'Development process',
    'Built dev/prod envs, seeded DB, translated sketches to code.',
    'Feedback',
    'Iterated with client; improved layout and CTA sections.',
    'Fine-tuning',
    'Polished visuals; optimized images for intended impact.',
    'Results',
    'Monitored results; provided support for bugs and edge cases.',
    'A 10% MoM total sales increase and international market expansion allowing the client to sell her products in Sweden, Germany and The Netherlands.',
    'Despite the dynamic nature of the project and the client''s adjustments, the final result was a source of mutual satisfaction. The successful collaboration on this project laid the foundation for future collaborations, demonstrating the value of open communication and a shared commitment to achieving the client''s vision.',
    'Total sales MoM',
    '+10% MoM total sales increase',
    'International orders',
    'Cross-borders orders from SE, DE and NL',
    NULL,
    NULL,
    'https://issasjewelry.com/'
);

-- Project 5: P-E-M: Breaking the Chains
INSERT INTO projects (
    project_id,
    project_name,
    project_logo_1,
    project_logo_2,
    project_description,
    project_overview_description_part_01,
    project_overview_description_part_02,
    project_overview_technologies,
    project_overview_duration,
    project_timeline_event_01_title,
    project_timeline_event_01,
    project_timeline_event_02_title,
    project_timeline_event_02,
    project_timeline_event_03_title,
    project_timeline_event_03,
    project_timeline_event_04_title,
    project_timeline_event_04,
    project_timeline_event_05_title,
    project_timeline_event_05,
    project_final_results_description_part_01,
    project_final_results_description_part_02,
    project_final_results_stat_01_title,
    project_final_results_stat_01,
    project_final_results_stat_02_title,
    project_final_results_stat_02,
    project_final_results_stat_03_title,
    project_final_results_stat_03,
    project_external_url
) VALUES (
    5,
    'P-E-M: Breaking the Chains',
    NULL,
    NULL,
    'Rebuilt and migrated the business site for P-E-M (Proyecto en Madera), a wood-based product company, allowing them to regain full control over their content by replacing an expensive and restrictive Britix CMS setup. The new solution is secure, fully containerized, and built with modern DevOps practices. Since launch, the client has seen a steady increase in site visits.',
    'For Proyecto en Madera (P-E-M), I migrated their site from a costly Bitrix CMS to a fully custom WordPress solution that empowers same-day updates.',
    'I also designed a Docker-based infra and deployed to a hardened Ubuntu droplet with WordPress, MariaDB, and Nginx, improving performance and organic traffic.',
    'Liquid, JavaScript, MySQL, HTML, CSS',
    '2 months',
    'Discovery & Planning',
    'Migrated from Bitrix to WordPress with goals of flexibility and cost.',
    'Theme Development',
    'Built custom theme enabling same-day edits to style and content.',
    'Infrastructure Setup',
    'Local Docker; deployed WordPress, MariaDB, and Nginx on hardened Ubuntu.',
    'Server Hardening',
    'SSH keys only, UFW, Fail2Ban, auto-updates, no root login.',
    'Launch & Results',
    'Migrated DB, enabled HTTPS, fixed redirects; traffic surged.',
    'Despite the dynamic nature of the project and the client''s adjustments, the final result was a source of mutual satisfaction.',
    'The successful collaboration on this project laid the foundation for future collaborations, demonstrating the value of open communication and a shared commitment to achieving the client''s vision.',
    'Lighthouse score',
    'Google Lighthouse score of +95%',
    'Site total visits',
    '+20% site total visits*',
    NULL,
    NULL,
    'https://www.proyectoenmadera.com.ar/'
);