CREATE TABLE projects (
    project_id SERIAL PRIMARY KEY,
    project_name TEXT NOT NULL,
    project_logo_1 BYTEA,
    project_logo_2 BYTEA,
    project_description TEXT,
    project_overview_description_part_01 TEXT,
    project_overview_description_part_02 TEXT,
    project_overview_technologies TEXT,
    project_overview_duration TEXT,
    project_timeline_event_01_title TEXT,
    project_timeline_event_01 TEXT,
    project_timeline_event_02_title TEXT,
    project_timeline_event_02 TEXT,
    project_timeline_event_03_title TEXT,
    project_timeline_event_03 TEXT,
    project_timeline_event_04_title TEXT,
    project_timeline_event_04 TEXT,
    project_timeline_event_05_title TEXT,
    project_timeline_event_05 TEXT,
    project_final_results_description_part_01 TEXT,
    project_final_results_description_part_02 TEXT,
    project_final_results_stat_01_title TEXT,
    project_final_results_stat_01 TEXT,
    project_final_results_stat_02_title TEXT,
    project_final_results_stat_02 TEXT,
    project_final_results_stat_03_title TEXT,
    project_final_results_stat_03 TEXT,
    project_external_url TEXT
);